### ISSUE TITLE
Broken install

### ISSUE THREAD

**Issue by aljazerzen** [edgedb/edgedb-python#398]
```
$ pip install edgedb==0.25.0a1
```
... fails with some warnings and this error:
```
      edgedb/datatypes/namedtuple.c: In function ‘EdgeNamedTuple_New’:                                                                                    
      edgedb/datatypes/namedtuple.c:78:25: error: lvalue required as left operand of assignment                                                           
         78 |             Py_TYPE(nt) = type;                                                                                                             
            |
```

It works with version 0.24.0, but edb has version 0.25.0a1 pinned for the build environment.

OS: Ubuntu 20.02
Python: 3.11.0
Cython: 0.29.32

@fantix can you help me out?

**Comment by fantix** [comment]
Oh we should probably just bump the pin, as this is already fixed in #375. Let me file a PR
